title: ""
email: "lukas.karrer26@gmail.com"
description: "Angehender Raumfahrt-Ingenieur | Prototyping, 3D-Druck, Embedded & KI"
baseurl: ""
url: "https://lukaskarrer.github.io"
theme: minima
plugins:
  - jekyll-feed

navigation:
  - title: "Start"
    url: "/"
  - title: "Projekte"
    url: "/projects/"
  - title: "Werkstatt & Tools"
    url: "/werkstatt/"
